services:
  patient-service:
    image: patient-service:latest
    container_name: patient-service
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patient_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-docker:9092

    ports:
      - "4000:4000"

    # depends_on:
    #   - patient-service-db

    networks:
      - internal

networks:
  internal:
    external: true
