spring.application.name=patient-service

server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5432/caresync
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
